name: Quality Gate
on:
  push:
    branches:
      - main

jobs:
  application-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: home-cooking
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - run: |
          make test

      - name: Install gocov
        run: go install github.com/axw/gocov/gocov@latest
  
      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          gocov test ./... > coverage/coverage.out

      - name: Merge coverage files
        run: gocov-merge coverage/*.out > coverage/merged.out

      - name: Convert coverage to JSON
        run: gocov convert coverage/merged.out | gocov-xml > coverage/coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
